more

diff --git a/chromium_code/all_changed_files/usrsctplib/bootstrap b/chromium_code/all_changed_files/usrsctplib/bootstrap
--- a/chromium_code/all_changed_files/usrsctplib/bootstrap
+++ b/chromium_code/all_changed_files/usrsctplib/bootstrap
@@ -1,3 +1,4 @@
+#! /bin/sh
 #
 # Copyright (C) 2011-2012 Michael Tuexen
 #
@@ -28,11 +29,38 @@
 # SUCH DAMAGE.
 #
 
-if COND_PROGRAMS
-MAYBEPROGRAMS = programs
-endif
+#bail out on error
+set -e
 
-SUBDIRS = usrsctplib $(MAYBEPROGRAMS)
-EXTRA_DIST = bootstrap Makefile.nmake
-ACLOCAL_AMFLAGS = -I m4
-# pkgconfig_DATA = usrsctp.pc
+#detect (g)libtoolize
+if which libtoolize >/dev/null
+then
+	_LIBTOOLIZE=`which libtoolize`
+elif which glibtoolize >/dev/null
+then
+	_LIBTOOLIZE=`which glibtoolize`
+else
+	echo "ERROR: I cannot find libtoolize or glibtoolize!"
+	exit 1
+fi
+
+#execute (g)libtoolize
+${_LIBTOOLIZE}
+
+#execute aclocal
+if [ -e /usr/local/share/aclocal ]
+then
+   aclocal -I /usr/local/share/aclocal
+elif [ -e /usr/share/aclocal ]
+then
+   aclocal -I /usr/share/aclocal
+else
+   aclocal
+fi
+
+#execute autoconf
+autoconf
+
+#generate the ./configure
+automake --foreign --add-missing --copy
+
